window.DASHBOARD_DATA = {
  "q3_regs": [
    {
      "centre": "Bolton",
      "jul_counting": 29,
      "jul_clcp": 0,
      "jul_fleet": 0,
      "jul_total": 29,
      "jul_target": 24,
      "aug_counting": 6,
      "aug_clcp": 0,
      "aug_fleet": 0,
      "aug_total": 6,
      "aug_target": 12,
      "sep_counting": 20,
      "sep_clcp": 0,
      "sep_fleet": 0,
      "sep_total": 20,
      "sep_target": 69,
      "qtr_counting": 55,
      "qtr_fleet": 0,
      "qtr_total": 55,
      "qtr_target": 105,
      "to_go": 50,
      "per_week": 4,
      "qtr_regs": 55,
      "target": 105,
      "regs_v_target": 0.5238095238
    },
    {
      "centre": "Bury",
      "jul_counting": 16,
      "jul_clcp": 0,
      "jul_fleet": 0,
      "jul_total": 16,
      "jul_target": 19,
      "aug_counting": 1,
      "aug_clcp": 0,
      "aug_fleet": 0,
      "aug_total": 1,
      "aug_target": 11,
      "sep_counting": 17,
      "sep_clcp": 0,
      "sep_fleet": 0,
      "sep_total": 17,
      "sep_target": 47,
      "qtr_counting": 34,
      "qtr_fleet": 0,
      "qtr_total": 34,
      "qtr_target": 77,
      "to_go": 43,
      "per_week": 4,
      "qtr_regs": 34,
      "target": 77,
      "regs_v_target": 0.4415584416
    },
    {
      "centre": "Rochdale",
      "jul_counting": 22,
      "jul_clcp": 0,
      "jul_fleet": 0,
      "jul_total": 22,
      "jul_target": 19,
      "aug_counting": 4,
      "aug_clcp": 0,
      "aug_fleet": 0,
      "aug_total": 4,
      "aug_target": 11,
      "sep_counting": 22,
      "sep_clcp": 0,
      "sep_fleet": 0,
      "sep_total": 22,
      "sep_target": 55,
      "qtr_counting": 48,
      "qtr_fleet": 0,
      "qtr_total": 48,
      "qtr_target": 85,
      "to_go": 37,
      "per_week": 3,
      "qtr_regs": 48,
      "target": 85,
      "regs_v_target": 0.5647058824
    },
    {
      "centre": "SQ",
      "jul_counting": 27,
      "jul_clcp": 0,
      "jul_fleet": 0,
      "jul_total": 27,
      "jul_target": 32,
      "aug_counting": 3,
      "aug_clcp": 0,
      "aug_fleet": 0,
      "aug_total": 3,
      "aug_target": 18,
      "sep_counting": 13,
      "sep_clcp": 0,
      "sep_fleet": 0,
      "sep_total": 13,
      "sep_target": 90,
      "qtr_counting": 43,
      "qtr_fleet": 0,
      "qtr_total": 43,
      "qtr_target": 140,
      "to_go": 97,
      "per_week": 8,
      "qtr_regs": 43,
      "target": 140,
      "regs_v_target": 0.3071428571
    },
    {
      "centre": "NORTH CDA",
      "jul_counting": 94,
      "jul_clcp": 0,
      "jul_fleet": 0,
      "jul_total": 94,
      "jul_target": 94,
      "aug_counting": 14,
      "aug_clcp": 0,
      "aug_fleet": 0,
      "aug_total": 14,
      "aug_target": 52,
      "sep_counting": 72,
      "sep_clcp": 0,
      "sep_fleet": 0,
      "sep_total": 72,
      "sep_target": 261,
      "qtr_counting": 180,
      "qtr_fleet": 0,
      "qtr_total": 180,
      "qtr_target": 407,
      "to_go": 227,
      "per_week": 18,
      "qtr_regs": 180,
      "target": 407,
      "regs_v_target": 0.4422604423
    },
    {
      "centre": "Bradford",
      "jul_counting": 25,
      "jul_clcp": 0,
      "jul_fleet": 4,
      "jul_total": 29,
      "jul_target": 22,
      "aug_counting": 8,
      "aug_clcp": 0,
      "aug_fleet": 2,
      "aug_total": 10,
      "aug_target": 13,
      "sep_counting": 16,
      "sep_clcp": 0,
      "sep_fleet": 2,
      "sep_total": 18,
      "sep_target": 70,
      "qtr_counting": 49,
      "qtr_fleet": 8,
      "qtr_total": 57,
      "qtr_target": 105,
      "to_go": 48,
      "per_week": 4,
      "qtr_regs": 57,
      "target": 105,
      "regs_v_target": 0.5428571429
    },
    {
      "centre": "Huddersfield",
      "jul_counting": 31,
      "jul_clcp": 0,
      "jul_fleet": 2,
      "jul_total": 33,
      "jul_target": 23,
      "aug_counting": 4,
      "aug_clcp": 0,
      "aug_fleet": 2,
      "aug_total": 6,
      "aug_target": 13,
      "sep_counting": 19,
      "sep_clcp": 0,
      "sep_fleet": 2,
      "sep_total": 21,
      "sep_target": 72,
      "qtr_counting": 54,
      "qtr_fleet": 6,
      "qtr_total": 60,
      "qtr_target": 108,
      "to_go": 48,
      "per_week": 4,
      "qtr_regs": 60,
      "target": 108,
      "regs_v_target": 0.5555555556
    },
    {
      "centre": "Silsden",
      "jul_counting": 6,
      "jul_clcp": 0,
      "jul_fleet": 0,
      "jul_total": 6,
      "jul_target": 8,
      "aug_counting": 2,
      "aug_clcp": 0,
      "aug_fleet": 0,
      "aug_total": 2,
      "aug_target": 3,
      "sep_counting": 1,
      "sep_clcp": 0,
      "sep_fleet": 0,
      "sep_total": 1,
      "sep_target": 23,
      "qtr_counting": 9,
      "qtr_fleet": 0,
      "qtr_total": 9,
      "qtr_target": 34,
      "to_go": 25,
      "per_week": 2,
      "qtr_regs": 9,
      "target": 34,
      "regs_v_target": 0.2647058824
    },
    {
      "centre": "WY CDA",
      "jul_counting": 62,
      "jul_clcp": 0,
      "jul_fleet": 6,
      "jul_total": 68,
      "jul_target": 53,
      "aug_counting": 14,
      "aug_clcp": 0,
      "aug_fleet": 4,
      "aug_total": 18,
      "aug_target": 29,
      "sep_counting": 36,
      "sep_clcp": 0,
      "sep_fleet": 4,
      "sep_total": 40,
      "sep_target": 165,
      "qtr_counting": 112,
      "qtr_fleet": 14,
      "qtr_total": 126,
      "qtr_target": 247,
      "to_go": 121,
      "per_week": 10,
      "qtr_regs": 126,
      "target": 247,
      "regs_v_target": 0.5101214575
    }
  ],
  "q3_non": [
    {
      "centre": "Salford",
      "jul_reg": 8,
      "jul_unreg": 67,
      "jul_total": 75,
      "jul_budget": 0,
      "aug_reg": 0,
      "aug_unreg": 18,
      "aug_total": 18,
      "aug_budget": 0,
      "sep_reg": 0,
      "sep_unreg": 4,
      "sep_total": 4,
      "sep_budget": 0,
      "qtr_reg": 8,
      "qtr_unreg": 89,
      "qtr_total": 97,
      "qtr_budget": 0
    },
    {
      "centre": "NORTH CDA",
      "jul_reg": 8,
      "jul_unreg": 67,
      "jul_total": 75,
      "jul_budget": 0,
      "aug_reg": 0,
      "aug_unreg": 18,
      "aug_total": 18,
      "aug_budget": 0,
      "sep_reg": 0,
      "sep_unreg": 4,
      "sep_total": 4,
      "sep_budget": 0,
      "qtr_reg": 8,
      "qtr_unreg": 89,
      "qtr_total": 97,
      "qtr_budget": 0
    },
    {
      "centre": "Bradford",
      "jul_reg": 0,
      "jul_unreg": 30,
      "jul_total": 30,
      "jul_budget": 0,
      "aug_reg": 0,
      "aug_unreg": 40,
      "aug_total": 40,
      "aug_budget": 0,
      "sep_reg": 0,
      "sep_unreg": 40,
      "sep_total": 40,
      "sep_budget": 0,
      "qtr_reg": 0,
      "qtr_unreg": 110,
      "qtr_total": 110,
      "qtr_budget": 0
    },
    {
      "centre": "WY CDA",
      "jul_reg": 0,
      "jul_unreg": 30,
      "jul_total": 30,
      "jul_budget": 0,
      "aug_reg": 0,
      "aug_unreg": 40,
      "aug_total": 40,
      "aug_budget": 0,
      "sep_reg": 0,
      "sep_unreg": 40,
      "sep_total": 40,
      "sep_budget": 0,
      "qtr_reg": 0,
      "qtr_unreg": 110,
      "qtr_total": 110,
      "qtr_budget": 0
    }
  ],
  "q3_used": [
    {
      "centre": "Bolton",
      "jul_counting": 12,
      "jul_target": 63,
      "aug_counting": 0,
      "aug_target": 62,
      "sep_counting": 0,
      "sep_target": 62,
      "qtr_counting": 12,
      "qtr_target": 187
    },
    {
      "centre": "Bury",
      "jul_counting": 8,
      "jul_target": 55,
      "aug_counting": 0,
      "aug_target": 54,
      "sep_counting": 0,
      "sep_target": 54,
      "qtr_counting": 8,
      "qtr_target": 163
    },
    {
      "centre": "Rochdale",
      "jul_counting": 5,
      "jul_target": 51,
      "aug_counting": 0,
      "aug_target": 50,
      "sep_counting": 0,
      "sep_target": 50,
      "qtr_counting": 5,
      "qtr_target": 151
    },
    {
      "centre": "SQ",
      "jul_counting": 9,
      "jul_target": 60,
      "aug_counting": 0,
      "aug_target": 59,
      "sep_counting": 0,
      "sep_target": 59,
      "qtr_counting": 9,
      "qtr_target": 178
    },
    {
      "centre": "NORTH CDA",
      "jul_counting": 34,
      "jul_target": 229,
      "aug_counting": 0,
      "aug_target": 225,
      "sep_counting": 0,
      "sep_target": 225,
      "qtr_counting": 34,
      "qtr_target": 679
    },
    {
      "centre": "Bradford",
      "jul_counting": 11,
      "jul_target": 36,
      "aug_counting": 0,
      "aug_target": 36,
      "sep_counting": 0,
      "sep_target": 36,
      "qtr_counting": 11,
      "qtr_target": 108
    },
    {
      "centre": "Huddersfield",
      "jul_counting": 12,
      "jul_target": 47,
      "aug_counting": 0,
      "aug_target": 46,
      "sep_counting": 0,
      "sep_target": 46,
      "qtr_counting": 12,
      "qtr_target": 139
    },
    {
      "centre": "Silsden",
      "jul_counting": 4,
      "jul_target": 22,
      "aug_counting": 0,
      "aug_target": 21,
      "sep_counting": 0,
      "sep_target": 21,
      "qtr_counting": 4,
      "qtr_target": 64
    },
    {
      "centre": "WY CDA",
      "jul_counting": 27,
      "jul_target": 105,
      "aug_counting": 0,
      "aug_target": 103,
      "sep_counting": 0,
      "sep_target": 103,
      "qtr_counting": 27,
      "qtr_target": 311
    }
  ],
  "q3_fleet": [
    {
      "centre": "Bolton",
      "regs": 0,
      "target": 7,
      "pct": 0,
      "active_orders": 0
    },
    {
      "centre": "Bury",
      "regs": 0,
      "target": 5,
      "pct": 0,
      "active_orders": 0
    },
    {
      "centre": "Rochdale",
      "regs": 0,
      "target": 6,
      "pct": 0,
      "active_orders": 0
    },
    {
      "centre": "SQ",
      "regs": 0,
      "target": 8,
      "pct": 0,
      "active_orders": 0
    },
    {
      "centre": "NORTH CDA",
      "regs": 0,
      "target": 26,
      "pct": 0,
      "active_orders": 0
    },
    {
      "centre": "Bradford",
      "regs": 1,
      "target": 6,
      "pct": 0.1666666667,
      "active_orders": 0
    },
    {
      "centre": "Huddersfield",
      "regs": 4,
      "target": 7,
      "pct": 0.5714285714,
      "active_orders": 0
    },
    {
      "centre": "Silsden",
      "regs": 0,
      "target": 2,
      "pct": 0,
      "active_orders": 0
    },
    {
      "centre": "WY CDA",
      "regs": 5,
      "target": 15,
      "pct": 0.3333333333,
      "active_orders": 0
    }
  ],
  "q2_regs": [
    {
      "centre": "Bolton",
      "apr_total": 26,
      "apr_target": 21,
      "may_total": 32,
      "may_target": 27,
      "jun_total": 43,
      "jun_target": 48,
      "qtr_counting": 99,
      "qtr_fleet": 2,
      "qtr_total": 101,
      "qtr_target": 96,
      "to_go": -5,
      "per_week": 9,
      "regs_v_target": 1.0521
    },
    {
      "centre": "Bury",
      "apr_total": 23,
      "apr_target": 15,
      "may_total": 28,
      "may_target": 20,
      "jun_total": 26,
      "jun_target": 36,
      "qtr_counting": 75,
      "qtr_fleet": 2,
      "qtr_total": 77,
      "qtr_target": 71,
      "to_go": -6,
      "per_week": 11,
      "regs_v_target": 1.0845
    },
    {
      "centre": "Rochdale",
      "apr_total": 22,
      "apr_target": 17,
      "may_total": 41,
      "may_target": 23,
      "jun_total": 27,
      "jun_target": 40,
      "qtr_counting": 90,
      "qtr_fleet": 0,
      "qtr_total": 90,
      "qtr_target": 80,
      "to_go": -10,
      "per_week": 18,
      "regs_v_target": 1.125
    },
    {
      "centre": "SQ",
      "apr_total": 52,
      "apr_target": 29,
      "may_total": 45,
      "may_target": 37,
      "jun_total": 51,
      "jun_target": 60,
      "qtr_counting": 125,
      "qtr_fleet": 23,
      "qtr_total": 148,
      "qtr_target": 126,
      "to_go": -22,
      "per_week": 39,
      "regs_v_target": 1.1746
    },
    {
      "centre": "NORTH CDA",
      "apr_total": 123,
      "apr_target": 82,
      "may_total": 146,
      "may_target": 107,
      "jun_total": 147,
      "jun_target": 184,
      "qtr_counting": 389,
      "qtr_fleet": 27,
      "qtr_total": 416,
      "qtr_target": 373,
      "to_go": -43,
      "per_week": 75,
      "regs_v_target": 1.1153
    },
    {
      "centre": "Bradford",
      "apr_total": 22,
      "apr_target": 22,
      "may_total": 27,
      "may_target": 26,
      "jun_total": 30,
      "jun_target": 44,
      "qtr_counting": 66,
      "qtr_fleet": 13,
      "qtr_total": 79,
      "qtr_target": 92,
      "to_go": 13,
      "per_week": -23,
      "regs_v_target": 0.8587
    },
    {
      "centre": "Huddersfield",
      "apr_total": 25,
      "apr_target": 21,
      "may_total": 38,
      "may_target": 27,
      "jun_total": 34,
      "jun_target": 49,
      "qtr_counting": 89,
      "qtr_fleet": 8,
      "qtr_total": 97,
      "qtr_target": 97,
      "to_go": 0,
      "per_week": 0,
      "regs_v_target": 1
    },
    {
      "centre": "Silsden",
      "apr_total": 6,
      "apr_target": 6,
      "may_total": 7,
      "may_target": 9,
      "jun_total": 17,
      "jun_target": 13,
      "qtr_counting": 30,
      "qtr_fleet": 0,
      "qtr_total": 30,
      "qtr_target": 28,
      "to_go": -2,
      "per_week": 4,
      "regs_v_target": 1.0714
    },
    {
      "centre": "WY CDA",
      "apr_total": 53,
      "apr_target": 49,
      "may_total": 72,
      "may_target": 62,
      "jun_total": 81,
      "jun_target": 106,
      "qtr_counting": 185,
      "qtr_fleet": 21,
      "qtr_total": 206,
      "qtr_target": 217,
      "to_go": 11,
      "per_week": -19,
      "regs_v_target": 0.9493
    }
  ],
  "q2_non": [
    {
      "centre": "NORTH CDA",
      "apr_total": 198,
      "may_total": 128,
      "jun_total": 328,
      "qtr_total": 654,
      "budget": 0
    },
    {
      "centre": "Bradford",
      "apr_total": 13,
      "may_total": 237,
      "jun_total": 34,
      "qtr_total": 284,
      "budget": 0
    },
    {
      "centre": "WY CDA",
      "apr_total": 13,
      "may_total": 237,
      "jun_total": 34,
      "qtr_total": 284,
      "budget": 0
    }
  ],
  "q2_used": [
    {
      "centre": "Bury",
      "apr_counting": 59,
      "apr_target": 51,
      "may_counting": 42,
      "may_target": 51,
      "jun_counting": 42,
      "jun_target": 54,
      "qtr_counting": 143,
      "qtr_target": 156
    },
    {
      "centre": "Rochdale",
      "apr_counting": 49,
      "apr_target": 47,
      "may_counting": 47,
      "may_target": 47,
      "jun_counting": 45,
      "jun_target": 50,
      "qtr_counting": 141,
      "qtr_target": 144
    },
    {
      "centre": "SQ",
      "apr_counting": 59,
      "apr_target": 56,
      "may_counting": 52,
      "may_target": 56,
      "jun_counting": 50,
      "jun_target": 59,
      "qtr_counting": 161,
      "qtr_target": 171
    },
    {
      "centre": "NORTH CDA",
      "apr_counting": 235,
      "apr_target": 213,
      "may_counting": 198,
      "may_target": 213,
      "jun_counting": 193,
      "jun_target": 225,
      "qtr_counting": 626,
      "qtr_target": 651
    },
    {
      "centre": "Bradford",
      "apr_counting": 40,
      "apr_target": 34,
      "may_counting": 37,
      "may_target": 34,
      "jun_counting": 40,
      "jun_target": 36,
      "qtr_counting": 117,
      "qtr_target": 104
    },
    {
      "centre": "Huddersfield",
      "apr_counting": 32,
      "apr_target": 44,
      "may_counting": 52,
      "may_target": 44,
      "jun_counting": 35,
      "jun_target": 46,
      "qtr_counting": 119,
      "qtr_target": 134
    },
    {
      "centre": "Silsden",
      "apr_counting": 20,
      "apr_target": 20,
      "may_counting": 20,
      "may_target": 20,
      "jun_counting": 31,
      "jun_target": 21,
      "qtr_counting": 71,
      "qtr_target": 61
    },
    {
      "centre": "WY CDA",
      "apr_counting": 92,
      "apr_target": 98,
      "may_counting": 109,
      "may_target": 98,
      "jun_counting": 106,
      "jun_target": 103,
      "qtr_counting": 307,
      "qtr_target": 299
    }
  ],
  "q3_fleet_monthly": [
    {
      "centre": "Bolton",
      "jul_fleet": 0,
      "aug_fleet": 0,
      "sep_fleet": 0,
      "qtr_fleet": 0,
      "bch_regs": 0,
      "bch_target": 7,
      "active_orders": 0
    },
    {
      "centre": "Bury",
      "jul_fleet": 0,
      "aug_fleet": 0,
      "sep_fleet": 0,
      "qtr_fleet": 0,
      "bch_regs": 0,
      "bch_target": 5,
      "active_orders": 0
    },
    {
      "centre": "Rochdale",
      "jul_fleet": 0,
      "aug_fleet": 0,
      "sep_fleet": 0,
      "qtr_fleet": 0,
      "bch_regs": 0,
      "bch_target": 6,
      "active_orders": 0
    },
    {
      "centre": "SQ",
      "jul_fleet": 0,
      "aug_fleet": 0,
      "sep_fleet": 0,
      "qtr_fleet": 0,
      "bch_regs": 0,
      "bch_target": 8,
      "active_orders": 0
    },
    {
      "centre": "NORTH CDA",
      "jul_fleet": 0,
      "aug_fleet": 0,
      "sep_fleet": 0,
      "qtr_fleet": 0,
      "bch_regs": 0,
      "bch_target": 26,
      "active_orders": 0
    },
    {
      "centre": "Bradford",
      "jul_fleet": 0,
      "aug_fleet": 0,
      "sep_fleet": 0,
      "qtr_fleet": 0,
      "bch_regs": 1,
      "bch_target": 6,
      "active_orders": 0
    },
    {
      "centre": "Huddersfield",
      "jul_fleet": 0,
      "aug_fleet": 0,
      "sep_fleet": 0,
      "qtr_fleet": 0,
      "bch_regs": 0,
      "bch_target": 7,
      "active_orders": 0
    },
    {
      "centre": "Silsden",
      "jul_fleet": 0,
      "aug_fleet": 0,
      "sep_fleet": 0,
      "qtr_fleet": 0,
      "bch_regs": 0,
      "bch_target": 2,
      "active_orders": 0
    },
    {
      "centre": "WY CDA",
      "jul_fleet": 0,
      "aug_fleet": 0,
      "sep_fleet": 0,
      "qtr_fleet": 0,
      "bch_regs": 1,
      "bch_target": 15,
      "active_orders": 0
    }
  ],
  "order_bank": [
    {
      "centre": "Bolton",
      "aso": 411,
      "q1_target": 119,
      "q2_target": 99,
      "q3_target": 108,
      "q4_target": 91,
      "cy26_target": 417,
      "jan_target": 29,
      "jan_orders": 51,
      "jan_diff": 22,
      "feb_target": 44,
      "feb_orders": 54,
      "feb_diff": 10,
      "mar_target": 46,
      "mar_orders": 33,
      "mar_diff": -13,
      "apr_target": 30,
      "apr_orders": 38,
      "apr_diff": 8,
      "may_target": 33,
      "may_orders": 35,
      "may_diff": 2,
      "jun_target": 36,
      "jun_orders": 41,
      "jun_diff": 5,
      "h1_target": 218,
      "h1_orders": 252,
      "h1_diff": 34,
      "h1_pct": 1.1559633027522935,
      "jul_target": 28,
      "jul_orders": 2,
      "jul_diff": -26,
      "aug_target": 41,
      "aug_orders": null,
      "aug_diff": -41,
      "sep_target": 39,
      "sep_orders": null,
      "sep_diff": -39,
      "oct_target": 28,
      "oct_orders": null,
      "oct_diff": -28,
      "nov_target": 33,
      "nov_orders": null,
      "nov_diff": -33,
      "dec_target": 30,
      "dec_orders": null,
      "dec_diff": -30,
      "h2_target": 199
    },
    {
      "centre": "Bury",
      "aso": 298,
      "q1_target": 87,
      "q2_target": 75,
      "q3_target": 77,
      "q4_target": 65,
      "cy26_target": 304,
      "jan_target": 21,
      "jan_orders": 35,
      "jan_diff": 14,
      "feb_target": 32,
      "feb_orders": 59,
      "feb_diff": 27,
      "mar_target": 34,
      "mar_orders": 35,
      "mar_diff": 1,
      "apr_target": 23,
      "apr_orders": 19,
      "apr_diff": -4,
      "may_target": 25,
      "may_orders": 26,
      "may_diff": 1,
      "jun_target": 27,
      "jun_orders": 24,
      "jun_diff": -3,
      "h1_target": 162,
      "h1_orders": 198,
      "h1_diff": 36,
      "h1_pct": 1.2222222222222223,
      "jul_target": 21,
      "jul_orders": 1,
      "jul_diff": -20,
      "aug_target": 29,
      "aug_orders": null,
      "aug_diff": -29,
      "sep_target": 27,
      "sep_orders": null,
      "sep_diff": -27,
      "oct_target": 20,
      "oct_orders": null,
      "oct_diff": -20,
      "nov_target": 23,
      "nov_orders": null,
      "nov_diff": -23,
      "dec_target": 22,
      "dec_orders": null,
      "dec_diff": -22,
      "h2_target": 142
    },
    {
      "centre": "Rochdale",
      "aso": 336,
      "q1_target": 97,
      "q2_target": 82,
      "q3_target": 87,
      "q4_target": 74,
      "cy26_target": 340,
      "jan_target": 23,
      "jan_orders": 43,
      "jan_diff": 20,
      "feb_target": 36,
      "feb_orders": 65,
      "feb_diff": 29,
      "mar_target": 38,
      "mar_orders": 39,
      "mar_diff": 1,
      "apr_target": 25,
      "apr_orders": 34,
      "apr_diff": 9,
      "may_target": 27,
      "may_orders": 25,
      "may_diff": -2,
      "jun_target": 30,
      "jun_orders": 38,
      "jun_diff": 8,
      "h1_target": 179,
      "h1_orders": 244,
      "h1_diff": 65,
      "h1_pct": 1.3631284916201116,
      "jul_target": 22,
      "jul_orders": 5,
      "jul_diff": -17,
      "aug_target": 33,
      "aug_orders": null,
      "aug_diff": -33,
      "sep_target": 32,
      "sep_orders": null,
      "sep_diff": -32,
      "oct_target": 22,
      "oct_orders": null,
      "oct_diff": -22,
      "nov_target": 27,
      "nov_orders": null,
      "nov_diff": -27,
      "dec_target": 25,
      "dec_orders": null,
      "dec_diff": -25,
      "h2_target": 161
    },
    {
      "centre": "SQ",
      "aso": 537,
      "q1_target": 152,
      "q2_target": 131,
      "q3_target": 143,
      "q4_target": 118,
      "cy26_target": 544,
      "jan_target": 38,
      "jan_orders": 56,
      "jan_diff": 18,
      "feb_target": 56,
      "feb_orders": 63,
      "feb_diff": 7,
      "mar_target": 58,
      "mar_orders": 76,
      "mar_diff": 18,
      "apr_target": 40,
      "apr_orders": 33,
      "apr_diff": -7,
      "may_target": 44,
      "may_orders": 40,
      "may_diff": -4,
      "jun_target": 47,
      "jun_orders": 53,
      "jun_diff": 6,
      "h1_target": 283,
      "h1_orders": 321,
      "h1_diff": 38,
      "h1_pct": 1.1342756183745584,
      "jul_target": 37,
      "jul_orders": 6,
      "jul_diff": -31,
      "aug_target": 55,
      "aug_orders": null,
      "aug_diff": -55,
      "sep_target": 51,
      "sep_orders": null,
      "sep_diff": -51,
      "oct_target": 37,
      "oct_orders": null,
      "oct_diff": -37,
      "nov_target": 43,
      "nov_orders": null,
      "nov_diff": -43,
      "dec_target": 38,
      "dec_orders": null,
      "dec_diff": -38,
      "h2_target": 261
    },
    {
      "centre": "Altrincham",
      "aso": 323,
      "q1_target": 91,
      "q2_target": 78,
      "q3_target": 89,
      "q4_target": 71,
      "cy26_target": 329,
      "jan_target": 22,
      "jan_orders": 45,
      "jan_diff": 23,
      "feb_target": 34,
      "feb_orders": 59,
      "feb_diff": 25,
      "mar_target": 35,
      "mar_orders": 29,
      "mar_diff": -6,
      "apr_target": 23,
      "apr_orders": 15,
      "apr_diff": -8,
      "may_target": 26,
      "may_orders": 21,
      "may_diff": -5,
      "jun_target": 29,
      "jun_orders": 28,
      "jun_diff": -1,
      "h1_target": 169,
      "h1_orders": 197,
      "h1_diff": 28,
      "h1_pct": 1.165680473372781,
      "jul_target": 23,
      "jul_orders": 1,
      "jul_diff": -22,
      "aug_target": 34,
      "aug_orders": null,
      "aug_diff": -34,
      "sep_target": 32,
      "sep_orders": null,
      "sep_diff": -32,
      "oct_target": 22,
      "oct_orders": null,
      "oct_diff": -22,
      "nov_target": 25,
      "nov_orders": null,
      "nov_diff": -25,
      "dec_target": 24,
      "dec_orders": null,
      "dec_diff": -24,
      "h2_target": 160
    },
    {
      "centre": "Denton",
      "aso": 355,
      "q1_target": 101,
      "q2_target": 87,
      "q3_target": 96,
      "q4_target": 78,
      "cy26_target": 362,
      "jan_target": 24,
      "jan_orders": 46,
      "jan_diff": 22,
      "feb_target": 37,
      "feb_orders": 64,
      "feb_diff": 27,
      "mar_target": 40,
      "mar_orders": 44,
      "mar_diff": 4,
      "apr_target": 26,
      "apr_orders": 29,
      "apr_diff": 3,
      "may_target": 29,
      "may_orders": 21,
      "may_diff": -8,
      "jun_target": 32,
      "jun_orders": 22,
      "jun_diff": -10,
      "h1_target": 188,
      "h1_orders": 226,
      "h1_diff": 38,
      "h1_pct": 1.202127659574468,
      "jul_target": 24,
      "jul_orders": 6,
      "jul_diff": -18,
      "aug_target": 37,
      "aug_orders": null,
      "aug_diff": -37,
      "sep_target": 35,
      "sep_orders": null,
      "sep_diff": -35,
      "oct_target": 24,
      "oct_orders": null,
      "oct_diff": -24,
      "nov_target": 28,
      "nov_orders": null,
      "nov_diff": -28,
      "dec_target": 26,
      "dec_orders": null,
      "dec_diff": -26,
      "h2_target": 174
    },
    {
      "centre": "Macclesfield",
      "aso": 357,
      "q1_target": 100,
      "q2_target": 87,
      "q3_target": 97,
      "q4_target": 80,
      "cy26_target": 364,
      "jan_target": 24,
      "jan_orders": 37,
      "jan_diff": 13,
      "feb_target": 37,
      "feb_orders": 64,
      "feb_diff": 27,
      "mar_target": 39,
      "mar_orders": 34,
      "mar_diff": -5,
      "apr_target": 26,
      "apr_orders": 22,
      "apr_diff": -4,
      "may_target": 29,
      "may_orders": 23,
      "may_diff": -6,
      "jun_target": 32,
      "jun_orders": 36,
      "jun_diff": 4,
      "h1_target": 187,
      "h1_orders": 216,
      "h1_diff": 29,
      "h1_pct": 1.1550802139037433,
      "jul_target": 25,
      "jul_orders": 3,
      "jul_diff": -22,
      "aug_target": 37,
      "aug_orders": null,
      "aug_diff": -37,
      "sep_target": 35,
      "sep_orders": null,
      "sep_diff": -35,
      "oct_target": 25,
      "oct_orders": null,
      "oct_diff": -25,
      "nov_target": 28,
      "nov_orders": null,
      "nov_diff": -28,
      "dec_target": 27,
      "dec_orders": null,
      "dec_diff": -27,
      "h2_target": 177
    },
    {
      "centre": "Stockport",
      "aso": 575,
      "q1_target": 160,
      "q2_target": 141,
      "q3_target": 153,
      "q4_target": 127,
      "cy26_target": 581,
      "jan_target": 39,
      "jan_orders": 64,
      "jan_diff": 25,
      "feb_target": 59,
      "feb_orders": 57,
      "feb_diff": -2,
      "mar_target": 62,
      "mar_orders": 88,
      "mar_diff": 26,
      "apr_target": 43,
      "apr_orders": 45,
      "apr_diff": 2,
      "may_target": 47,
      "may_orders": 28,
      "may_diff": -19,
      "jun_target": 51,
      "jun_orders": 55,
      "jun_diff": 4,
      "h1_target": 301,
      "h1_orders": 337,
      "h1_diff": 36,
      "h1_pct": 1.1196013289036544,
      "jul_target": 39,
      "jul_orders": 4,
      "jul_diff": -35,
      "aug_target": 59,
      "aug_orders": null,
      "aug_diff": -59,
      "sep_target": 55,
      "sep_orders": null,
      "sep_diff": -55,
      "oct_target": 40,
      "oct_orders": null,
      "oct_diff": -40,
      "nov_target": 45,
      "nov_orders": null,
      "nov_diff": -45,
      "dec_target": 42,
      "dec_orders": null,
      "dec_diff": -42,
      "h2_target": 280
    },
    {
      "centre": "Bradford",
      "aso": 397,
      "q1_target": 112,
      "q2_target": 95,
      "q3_target": 107,
      "q4_target": 88,
      "cy26_target": 402,
      "jan_target": 28,
      "jan_orders": 34,
      "jan_diff": 6,
      "feb_target": 41,
      "feb_orders": 42,
      "feb_diff": 1,
      "mar_target": 43,
      "mar_orders": 44,
      "mar_diff": 1,
      "apr_target": 29,
      "apr_orders": 34,
      "apr_diff": 5,
      "may_target": 31,
      "may_orders": 24,
      "may_diff": -7,
      "jun_target": 35,
      "jun_orders": 45,
      "jun_diff": 10,
      "h1_target": 207,
      "h1_orders": 223,
      "h1_diff": 16,
      "h1_pct": 1.077294685990338,
      "jul_target": 27,
      "jul_orders": 0,
      "jul_diff": -27,
      "aug_target": 41,
      "aug_orders": null,
      "aug_diff": -41,
      "sep_target": 39,
      "sep_orders": null,
      "sep_diff": -39,
      "oct_target": 28,
      "oct_orders": null,
      "oct_diff": -28,
      "nov_target": 31,
      "nov_orders": null,
      "nov_diff": -31,
      "dec_target": 29,
      "dec_orders": null,
      "dec_diff": -29,
      "h2_target": 195
    },
    {
      "centre": "Huddersfield",
      "aso": 411,
      "q1_target": 116,
      "q2_target": 101,
      "q3_target": 108,
      "q4_target": 92,
      "cy26_target": 417,
      "jan_target": 28,
      "jan_orders": 56,
      "jan_diff": 28,
      "feb_target": 43,
      "feb_orders": 57,
      "feb_diff": 14,
      "mar_target": 45,
      "mar_orders": 46,
      "mar_diff": 1,
      "apr_target": 31,
      "apr_orders": 27,
      "apr_diff": -4,
      "may_target": 33,
      "may_orders": 28,
      "may_diff": -5,
      "jun_target": 37,
      "jun_orders": 33,
      "jun_diff": -4,
      "h1_target": 217,
      "h1_orders": 247,
      "h1_diff": 30,
      "h1_pct": 1.1382488479262673,
      "jul_target": 27,
      "jul_orders": 6,
      "jul_diff": -21,
      "aug_target": 41,
      "aug_orders": null,
      "aug_diff": -41,
      "sep_target": 40,
      "sep_orders": null,
      "sep_diff": -40,
      "oct_target": 28,
      "oct_orders": null,
      "oct_diff": -28,
      "nov_target": 33,
      "nov_orders": null,
      "nov_diff": -33,
      "dec_target": 31,
      "dec_orders": null,
      "dec_diff": -31,
      "h2_target": 200
    },
    {
      "centre": "Silsden",
      "aso": 132,
      "q1_target": 41,
      "q2_target": 31,
      "q3_target": 35,
      "q4_target": 32,
      "cy26_target": 139,
      "jan_target": 11,
      "jan_orders": 24,
      "jan_diff": 13,
      "feb_target": 15,
      "feb_orders": 12,
      "feb_diff": -3,
      "mar_target": 15,
      "mar_orders": 21,
      "mar_diff": 6,
      "apr_target": 9,
      "apr_orders": 5,
      "apr_diff": -4,
      "may_target": 11,
      "may_orders": 9,
      "may_diff": -2,
      "jun_target": 11,
      "jun_orders": 13,
      "jun_diff": 2,
      "h1_target": 72,
      "h1_orders": 84,
      "h1_diff": 12,
      "h1_pct": 1.1666666666666667,
      "jul_target": 9,
      "jul_orders": 0,
      "jul_diff": -9,
      "aug_target": 13,
      "aug_orders": null,
      "aug_diff": -13,
      "sep_target": 13,
      "sep_orders": null,
      "sep_diff": -13,
      "oct_target": 10,
      "oct_orders": null,
      "oct_diff": -10,
      "nov_target": 11,
      "nov_orders": null,
      "nov_diff": -11,
      "dec_target": 11,
      "dec_orders": null,
      "dec_diff": -11,
      "h2_target": 67
    }
  ],
  "sales_activity": [
    {
      "centre": "Bolton",
      "new_enquiries": 11,
      "new_test_drives": 6,
      "new_os": 3,
      "new_orders": 2,
      "used_enquiries": 26,
      "used_test_drives": 15,
      "used_os": 17,
      "used_orders": 12,
      "total_enquiries": 37,
      "total_test_drives": 21,
      "total_os": 20,
      "total_orders": 14,
      "lost_op_req": 0,
      "confirmed_orders": 0,
      "delivered": 21,
      "lost_opportunities": 26,
      "td_ratio": 0.57,
      "orders_ratio": 0.38,
      "os_ratio": 0.54
    },
    {
      "centre": "Bradford",
      "new_enquiries": 8,
      "new_test_drives": 1,
      "new_os": 0,
      "new_orders": 0,
      "used_enquiries": 24,
      "used_test_drives": 13,
      "used_os": 11,
      "used_orders": 11,
      "total_enquiries": 32,
      "total_test_drives": 14,
      "total_os": 11,
      "total_orders": 11,
      "lost_op_req": 0,
      "confirmed_orders": 0,
      "delivered": 12,
      "lost_opportunities": 23,
      "td_ratio": 0.44,
      "orders_ratio": 0.34,
      "os_ratio": 0.34
    },
    {
      "centre": "Bury",
      "new_enquiries": 8,
      "new_test_drives": 4,
      "new_os": 7,
      "new_orders": 4,
      "used_enquiries": 25,
      "used_test_drives": 8,
      "used_os": 9,
      "used_orders": 7,
      "total_enquiries": 33,
      "total_test_drives": 12,
      "total_os": 16,
      "total_orders": 11,
      "lost_op_req": 0,
      "confirmed_orders": 0,
      "delivered": 12,
      "lost_opportunities": 35,
      "td_ratio": 0.36,
      "orders_ratio": 0.33,
      "os_ratio": 0.48
    },
    {
      "centre": "Huddersfield",
      "new_enquiries": 12,
      "new_test_drives": 6,
      "new_os": 9,
      "new_orders": 3,
      "used_enquiries": 21,
      "used_test_drives": 9,
      "used_os": 14,
      "used_orders": 11,
      "total_enquiries": 33,
      "total_test_drives": 15,
      "total_os": 23,
      "total_orders": 14,
      "lost_op_req": 0,
      "confirmed_orders": 0,
      "delivered": 11,
      "lost_opportunities": 17,
      "td_ratio": 0.45,
      "orders_ratio": 0.42,
      "os_ratio": 0.7
    },
    {
      "centre": "Rochdale",
      "new_enquiries": 13,
      "new_test_drives": 5,
      "new_os": 4,
      "new_orders": 5,
      "used_enquiries": 19,
      "used_test_drives": 8,
      "used_os": 15,
      "used_orders": 7,
      "total_enquiries": 32,
      "total_test_drives": 13,
      "total_os": 19,
      "total_orders": 12,
      "lost_op_req": 1,
      "confirmed_orders": 0,
      "delivered": 8,
      "lost_opportunities": 22,
      "td_ratio": 0.41,
      "orders_ratio": 0.38,
      "os_ratio": 0.59
    },
    {
      "centre": "SQ",
      "new_enquiries": 22,
      "new_test_drives": 4,
      "new_os": 4,
      "new_orders": 2,
      "used_enquiries": 18,
      "used_test_drives": 7,
      "used_os": 12,
      "used_orders": 10,
      "total_enquiries": 40,
      "total_test_drives": 11,
      "total_os": 16,
      "total_orders": 12,
      "lost_op_req": 0,
      "confirmed_orders": 0,
      "delivered": 12,
      "lost_opportunities": 34,
      "td_ratio": 0.28,
      "orders_ratio": 0.3,
      "os_ratio": 0.4
    },
    {
      "centre": "Silsden",
      "new_enquiries": 2,
      "new_test_drives": 1,
      "new_os": 1,
      "new_orders": 0,
      "used_enquiries": 14,
      "used_test_drives": 3,
      "used_os": 1,
      "used_orders": 1,
      "total_enquiries": 16,
      "total_test_drives": 4,
      "total_os": 2,
      "total_orders": 1,
      "lost_op_req": 0,
      "confirmed_orders": 0,
      "delivered": 8,
      "lost_opportunities": 6,
      "td_ratio": 0.25,
      "orders_ratio": 0.06,
      "os_ratio": 0.12
    }
  ],
  "user_sites": [
    "Bolton",
    "Bury",
    "Rochdale",
    "SQ",
    "Bradford",
    "Huddersfield",
    "Silsden"
  ],
  "dashboard_regs": [
    {
      "centre": "Bolton",
      "jul_counting": 29,
      "jul_clcp": 0,
      "jul_fleet": 0,
      "jul_total": 29,
      "jul_target": 24,
      "aug_counting": 6,
      "aug_clcp": 0,
      "aug_fleet": 0,
      "aug_total": 6,
      "aug_target": 12,
      "sep_counting": 20,
      "sep_clcp": 0,
      "sep_fleet": 0,
      "sep_total": 20,
      "sep_target": 69,
      "qtr_counting": 55,
      "qtr_fleet": 0,
      "qtr_total": 55,
      "qtr_target": 105,
      "to_go": 50,
      "per_week": 4,
      "qtr_regs": 55,
      "target": 105,
      "regs_v_target": 0.5238095238
    },
    {
      "centre": "Bury",
      "jul_counting": 16,
      "jul_clcp": 0,
      "jul_fleet": 0,
      "jul_total": 16,
      "jul_target": 19,
      "aug_counting": 1,
      "aug_clcp": 0,
      "aug_fleet": 0,
      "aug_total": 1,
      "aug_target": 11,
      "sep_counting": 17,
      "sep_clcp": 0,
      "sep_fleet": 0,
      "sep_total": 17,
      "sep_target": 47,
      "qtr_counting": 34,
      "qtr_fleet": 0,
      "qtr_total": 34,
      "qtr_target": 77,
      "to_go": 43,
      "per_week": 4,
      "qtr_regs": 34,
      "target": 77,
      "regs_v_target": 0.4415584416
    },
    {
      "centre": "Rochdale",
      "jul_counting": 22,
      "jul_clcp": 0,
      "jul_fleet": 0,
      "jul_total": 22,
      "jul_target": 19,
      "aug_counting": 4,
      "aug_clcp": 0,
      "aug_fleet": 0,
      "aug_total": 4,
      "aug_target": 11,
      "sep_counting": 22,
      "sep_clcp": 0,
      "sep_fleet": 0,
      "sep_total": 22,
      "sep_target": 55,
      "qtr_counting": 48,
      "qtr_fleet": 0,
      "qtr_total": 48,
      "qtr_target": 85,
      "to_go": 37,
      "per_week": 3,
      "qtr_regs": 48,
      "target": 85,
      "regs_v_target": 0.5647058824
    },
    {
      "centre": "SQ",
      "jul_counting": 27,
      "jul_clcp": 0,
      "jul_fleet": 0,
      "jul_total": 27,
      "jul_target": 32,
      "aug_counting": 3,
      "aug_clcp": 0,
      "aug_fleet": 0,
      "aug_total": 3,
      "aug_target": 18,
      "sep_counting": 13,
      "sep_clcp": 0,
      "sep_fleet": 0,
      "sep_total": 13,
      "sep_target": 90,
      "qtr_counting": 43,
      "qtr_fleet": 0,
      "qtr_total": 43,
      "qtr_target": 140,
      "to_go": 97,
      "per_week": 8,
      "qtr_regs": 43,
      "target": 140,
      "regs_v_target": 0.3071428571
    },
    {
      "centre": "Bradford",
      "jul_counting": 25,
      "jul_clcp": 0,
      "jul_fleet": 4,
      "jul_total": 29,
      "jul_target": 22,
      "aug_counting": 8,
      "aug_clcp": 0,
      "aug_fleet": 2,
      "aug_total": 10,
      "aug_target": 13,
      "sep_counting": 16,
      "sep_clcp": 0,
      "sep_fleet": 2,
      "sep_total": 18,
      "sep_target": 70,
      "qtr_counting": 49,
      "qtr_fleet": 8,
      "qtr_total": 57,
      "qtr_target": 105,
      "to_go": 48,
      "per_week": 4,
      "qtr_regs": 57,
      "target": 105,
      "regs_v_target": 0.5428571429
    },
    {
      "centre": "Huddersfield",
      "jul_counting": 31,
      "jul_clcp": 0,
      "jul_fleet": 2,
      "jul_total": 33,
      "jul_target": 23,
      "aug_counting": 4,
      "aug_clcp": 0,
      "aug_fleet": 2,
      "aug_total": 6,
      "aug_target": 13,
      "sep_counting": 19,
      "sep_clcp": 0,
      "sep_fleet": 2,
      "sep_total": 21,
      "sep_target": 72,
      "qtr_counting": 54,
      "qtr_fleet": 6,
      "qtr_total": 60,
      "qtr_target": 108,
      "to_go": 48,
      "per_week": 4,
      "qtr_regs": 60,
      "target": 108,
      "regs_v_target": 0.5555555556
    },
    {
      "centre": "Silsden",
      "jul_counting": 6,
      "jul_clcp": 0,
      "jul_fleet": 0,
      "jul_total": 6,
      "jul_target": 8,
      "aug_counting": 2,
      "aug_clcp": 0,
      "aug_fleet": 0,
      "aug_total": 2,
      "aug_target": 3,
      "sep_counting": 1,
      "sep_clcp": 0,
      "sep_fleet": 0,
      "sep_total": 1,
      "sep_target": 23,
      "qtr_counting": 9,
      "qtr_fleet": 0,
      "qtr_total": 9,
      "qtr_target": 34,
      "to_go": 25,
      "per_week": 2,
      "qtr_regs": 9,
      "target": 34,
      "regs_v_target": 0.2647058824
    }
  ],
  "dashboard_used": [
    {
      "centre": "Bolton",
      "jul_counting": 12,
      "jul_target": 63,
      "aug_counting": 0,
      "aug_target": 62,
      "sep_counting": 0,
      "sep_target": 62,
      "qtr_counting": 12,
      "qtr_target": 187
    },
    {
      "centre": "Bury",
      "jul_counting": 8,
      "jul_target": 55,
      "aug_counting": 0,
      "aug_target": 54,
      "sep_counting": 0,
      "sep_target": 54,
      "qtr_counting": 8,
      "qtr_target": 163
    },
    {
      "centre": "Rochdale",
      "jul_counting": 5,
      "jul_target": 51,
      "aug_counting": 0,
      "aug_target": 50,
      "sep_counting": 0,
      "sep_target": 50,
      "qtr_counting": 5,
      "qtr_target": 151
    },
    {
      "centre": "SQ",
      "jul_counting": 9,
      "jul_target": 60,
      "aug_counting": 0,
      "aug_target": 59,
      "sep_counting": 0,
      "sep_target": 59,
      "qtr_counting": 9,
      "qtr_target": 178
    },
    {
      "centre": "Bradford",
      "jul_counting": 11,
      "jul_target": 36,
      "aug_counting": 0,
      "aug_target": 36,
      "sep_counting": 0,
      "sep_target": 36,
      "qtr_counting": 11,
      "qtr_target": 108
    },
    {
      "centre": "Huddersfield",
      "jul_counting": 12,
      "jul_target": 47,
      "aug_counting": 0,
      "aug_target": 46,
      "sep_counting": 0,
      "sep_target": 46,
      "qtr_counting": 12,
      "qtr_target": 139
    },
    {
      "centre": "Silsden",
      "jul_counting": 4,
      "jul_target": 22,
      "aug_counting": 0,
      "aug_target": 21,
      "sep_counting": 0,
      "sep_target": 21,
      "qtr_counting": 4,
      "qtr_target": 64
    }
  ],
  "dashboard_orders": [
    {
      "centre": "Bolton",
      "aso": 411,
      "q1_target": 119,
      "q2_target": 99,
      "q3_target": 108,
      "q4_target": 91,
      "cy26_target": 417,
      "jan_target": 29,
      "jan_orders": 51,
      "jan_diff": 22,
      "feb_target": 44,
      "feb_orders": 54,
      "feb_diff": 10,
      "mar_target": 46,
      "mar_orders": 33,
      "mar_diff": -13,
      "apr_target": 30,
      "apr_orders": 38,
      "apr_diff": 8,
      "may_target": 33,
      "may_orders": 35,
      "may_diff": 2,
      "jun_target": 36,
      "jun_orders": 41,
      "jun_diff": 5,
      "h1_target": 218,
      "h1_orders": 252,
      "h1_diff": 34,
      "h1_pct": 1.1559633027522935,
      "jul_target": 28,
      "jul_orders": 2,
      "jul_diff": -26,
      "aug_target": 41,
      "aug_orders": null,
      "aug_diff": -41,
      "sep_target": 39,
      "sep_orders": null,
      "sep_diff": -39,
      "oct_target": 28,
      "oct_orders": null,
      "oct_diff": -28,
      "nov_target": 33,
      "nov_orders": null,
      "nov_diff": -33,
      "dec_target": 30,
      "dec_orders": null,
      "dec_diff": -30,
      "h2_target": 199
    },
    {
      "centre": "Bury",
      "aso": 298,
      "q1_target": 87,
      "q2_target": 75,
      "q3_target": 77,
      "q4_target": 65,
      "cy26_target": 304,
      "jan_target": 21,
      "jan_orders": 35,
      "jan_diff": 14,
      "feb_target": 32,
      "feb_orders": 59,
      "feb_diff": 27,
      "mar_target": 34,
      "mar_orders": 35,
      "mar_diff": 1,
      "apr_target": 23,
      "apr_orders": 19,
      "apr_diff": -4,
      "may_target": 25,
      "may_orders": 26,
      "may_diff": 1,
      "jun_target": 27,
      "jun_orders": 24,
      "jun_diff": -3,
      "h1_target": 162,
      "h1_orders": 198,
      "h1_diff": 36,
      "h1_pct": 1.2222222222222223,
      "jul_target": 21,
      "jul_orders": 1,
      "jul_diff": -20,
      "aug_target": 29,
      "aug_orders": null,
      "aug_diff": -29,
      "sep_target": 27,
      "sep_orders": null,
      "sep_diff": -27,
      "oct_target": 20,
      "oct_orders": null,
      "oct_diff": -20,
      "nov_target": 23,
      "nov_orders": null,
      "nov_diff": -23,
      "dec_target": 22,
      "dec_orders": null,
      "dec_diff": -22,
      "h2_target": 142
    },
    {
      "centre": "Rochdale",
      "aso": 336,
      "q1_target": 97,
      "q2_target": 82,
      "q3_target": 87,
      "q4_target": 74,
      "cy26_target": 340,
      "jan_target": 23,
      "jan_orders": 43,
      "jan_diff": 20,
      "feb_target": 36,
      "feb_orders": 65,
      "feb_diff": 29,
      "mar_target": 38,
      "mar_orders": 39,
      "mar_diff": 1,
      "apr_target": 25,
      "apr_orders": 34,
      "apr_diff": 9,
      "may_target": 27,
      "may_orders": 25,
      "may_diff": -2,
      "jun_target": 30,
      "jun_orders": 38,
      "jun_diff": 8,
      "h1_target": 179,
      "h1_orders": 244,
      "h1_diff": 65,
      "h1_pct": 1.3631284916201116,
      "jul_target": 22,
      "jul_orders": 5,
      "jul_diff": -17,
      "aug_target": 33,
      "aug_orders": null,
      "aug_diff": -33,
      "sep_target": 32,
      "sep_orders": null,
      "sep_diff": -32,
      "oct_target": 22,
      "oct_orders": null,
      "oct_diff": -22,
      "nov_target": 27,
      "nov_orders": null,
      "nov_diff": -27,
      "dec_target": 25,
      "dec_orders": null,
      "dec_diff": -25,
      "h2_target": 161
    },
    {
      "centre": "SQ",
      "aso": 537,
      "q1_target": 152,
      "q2_target": 131,
      "q3_target": 143,
      "q4_target": 118,
      "cy26_target": 544,
      "jan_target": 38,
      "jan_orders": 56,
      "jan_diff": 18,
      "feb_target": 56,
      "feb_orders": 63,
      "feb_diff": 7,
      "mar_target": 58,
      "mar_orders": 76,
      "mar_diff": 18,
      "apr_target": 40,
      "apr_orders": 33,
      "apr_diff": -7,
      "may_target": 44,
      "may_orders": 40,
      "may_diff": -4,
      "jun_target": 47,
      "jun_orders": 53,
      "jun_diff": 6,
      "h1_target": 283,
      "h1_orders": 321,
      "h1_diff": 38,
      "h1_pct": 1.1342756183745584,
      "jul_target": 37,
      "jul_orders": 6,
      "jul_diff": -31,
      "aug_target": 55,
      "aug_orders": null,
      "aug_diff": -55,
      "sep_target": 51,
      "sep_orders": null,
      "sep_diff": -51,
      "oct_target": 37,
      "oct_orders": null,
      "oct_diff": -37,
      "nov_target": 43,
      "nov_orders": null,
      "nov_diff": -43,
      "dec_target": 38,
      "dec_orders": null,
      "dec_diff": -38,
      "h2_target": 261
    },
    {
      "centre": "Bradford",
      "aso": 397,
      "q1_target": 112,
      "q2_target": 95,
      "q3_target": 107,
      "q4_target": 88,
      "cy26_target": 402,
      "jan_target": 28,
      "jan_orders": 34,
      "jan_diff": 6,
      "feb_target": 41,
      "feb_orders": 42,
      "feb_diff": 1,
      "mar_target": 43,
      "mar_orders": 44,
      "mar_diff": 1,
      "apr_target": 29,
      "apr_orders": 34,
      "apr_diff": 5,
      "may_target": 31,
      "may_orders": 24,
      "may_diff": -7,
      "jun_target": 35,
      "jun_orders": 45,
      "jun_diff": 10,
      "h1_target": 207,
      "h1_orders": 223,
      "h1_diff": 16,
      "h1_pct": 1.077294685990338,
      "jul_target": 27,
      "jul_orders": 0,
      "jul_diff": -27,
      "aug_target": 41,
      "aug_orders": null,
      "aug_diff": -41,
      "sep_target": 39,
      "sep_orders": null,
      "sep_diff": -39,
      "oct_target": 28,
      "oct_orders": null,
      "oct_diff": -28,
      "nov_target": 31,
      "nov_orders": null,
      "nov_diff": -31,
      "dec_target": 29,
      "dec_orders": null,
      "dec_diff": -29,
      "h2_target": 195
    },
    {
      "centre": "Huddersfield",
      "aso": 411,
      "q1_target": 116,
      "q2_target": 101,
      "q3_target": 108,
      "q4_target": 92,
      "cy26_target": 417,
      "jan_target": 28,
      "jan_orders": 56,
      "jan_diff": 28,
      "feb_target": 43,
      "feb_orders": 57,
      "feb_diff": 14,
      "mar_target": 45,
      "mar_orders": 46,
      "mar_diff": 1,
      "apr_target": 31,
      "apr_orders": 27,
      "apr_diff": -4,
      "may_target": 33,
      "may_orders": 28,
      "may_diff": -5,
      "jun_target": 37,
      "jun_orders": 33,
      "jun_diff": -4,
      "h1_target": 217,
      "h1_orders": 247,
      "h1_diff": 30,
      "h1_pct": 1.1382488479262673,
      "jul_target": 27,
      "jul_orders": 6,
      "jul_diff": -21,
      "aug_target": 41,
      "aug_orders": null,
      "aug_diff": -41,
      "sep_target": 40,
      "sep_orders": null,
      "sep_diff": -40,
      "oct_target": 28,
      "oct_orders": null,
      "oct_diff": -28,
      "nov_target": 33,
      "nov_orders": null,
      "nov_diff": -33,
      "dec_target": 31,
      "dec_orders": null,
      "dec_diff": -31,
      "h2_target": 200
    },
    {
      "centre": "Silsden",
      "aso": 132,
      "q1_target": 41,
      "q2_target": 31,
      "q3_target": 35,
      "q4_target": 32,
      "cy26_target": 139,
      "jan_target": 11,
      "jan_orders": 24,
      "jan_diff": 13,
      "feb_target": 15,
      "feb_orders": 12,
      "feb_diff": -3,
      "mar_target": 15,
      "mar_orders": 21,
      "mar_diff": 6,
      "apr_target": 9,
      "apr_orders": 5,
      "apr_diff": -4,
      "may_target": 11,
      "may_orders": 9,
      "may_diff": -2,
      "jun_target": 11,
      "jun_orders": 13,
      "jun_diff": 2,
      "h1_target": 72,
      "h1_orders": 84,
      "h1_diff": 12,
      "h1_pct": 1.1666666666666667,
      "jul_target": 9,
      "jul_orders": 0,
      "jul_diff": -9,
      "aug_target": 13,
      "aug_orders": null,
      "aug_diff": -13,
      "sep_target": 13,
      "sep_orders": null,
      "sep_diff": -13,
      "oct_target": 10,
      "oct_orders": null,
      "oct_diff": -10,
      "nov_target": 11,
      "nov_orders": null,
      "nov_diff": -11,
      "dec_target": 11,
      "dec_orders": null,
      "dec_diff": -11,
      "h2_target": 67
    }
  ],
  "dashboard_activity": [
    {
      "centre": "Bolton",
      "new_enquiries": 11,
      "new_test_drives": 6,
      "new_os": 3,
      "new_orders": 2,
      "used_enquiries": 26,
      "used_test_drives": 15,
      "used_os": 17,
      "used_orders": 12,
      "total_enquiries": 37,
      "total_test_drives": 21,
      "total_os": 20,
      "total_orders": 14,
      "lost_op_req": 0,
      "confirmed_orders": 0,
      "delivered": 21,
      "lost_opportunities": 26,
      "td_ratio": 0.57,
      "orders_ratio": 0.38,
      "os_ratio": 0.54
    },
    {
      "centre": "Bradford",
      "new_enquiries": 8,
      "new_test_drives": 1,
      "new_os": 0,
      "new_orders": 0,
      "used_enquiries": 24,
      "used_test_drives": 13,
      "used_os": 11,
      "used_orders": 11,
      "total_enquiries": 32,
      "total_test_drives": 14,
      "total_os": 11,
      "total_orders": 11,
      "lost_op_req": 0,
      "confirmed_orders": 0,
      "delivered": 12,
      "lost_opportunities": 23,
      "td_ratio": 0.44,
      "orders_ratio": 0.34,
      "os_ratio": 0.34
    },
    {
      "centre": "Bury",
      "new_enquiries": 8,
      "new_test_drives": 4,
      "new_os": 7,
      "new_orders": 4,
      "used_enquiries": 25,
      "used_test_drives": 8,
      "used_os": 9,
      "used_orders": 7,
      "total_enquiries": 33,
      "total_test_drives": 12,
      "total_os": 16,
      "total_orders": 11,
      "lost_op_req": 0,
      "confirmed_orders": 0,
      "delivered": 12,
      "lost_opportunities": 35,
      "td_ratio": 0.36,
      "orders_ratio": 0.33,
      "os_ratio": 0.48
    },
    {
      "centre": "Huddersfield",
      "new_enquiries": 12,
      "new_test_drives": 6,
      "new_os": 9,
      "new_orders": 3,
      "used_enquiries": 21,
      "used_test_drives": 9,
      "used_os": 14,
      "used_orders": 11,
      "total_enquiries": 33,
      "total_test_drives": 15,
      "total_os": 23,
      "total_orders": 14,
      "lost_op_req": 0,
      "confirmed_orders": 0,
      "delivered": 11,
      "lost_opportunities": 17,
      "td_ratio": 0.45,
      "orders_ratio": 0.42,
      "os_ratio": 0.7
    },
    {
      "centre": "Rochdale",
      "new_enquiries": 13,
      "new_test_drives": 5,
      "new_os": 4,
      "new_orders": 5,
      "used_enquiries": 19,
      "used_test_drives": 8,
      "used_os": 15,
      "used_orders": 7,
      "total_enquiries": 32,
      "total_test_drives": 13,
      "total_os": 19,
      "total_orders": 12,
      "lost_op_req": 1,
      "confirmed_orders": 0,
      "delivered": 8,
      "lost_opportunities": 22,
      "td_ratio": 0.41,
      "orders_ratio": 0.38,
      "os_ratio": 0.59
    },
    {
      "centre": "SQ",
      "new_enquiries": 22,
      "new_test_drives": 4,
      "new_os": 4,
      "new_orders": 2,
      "used_enquiries": 18,
      "used_test_drives": 7,
      "used_os": 12,
      "used_orders": 10,
      "total_enquiries": 40,
      "total_test_drives": 11,
      "total_os": 16,
      "total_orders": 12,
      "lost_op_req": 0,
      "confirmed_orders": 0,
      "delivered": 12,
      "lost_opportunities": 34,
      "td_ratio": 0.28,
      "orders_ratio": 0.3,
      "os_ratio": 0.4
    },
    {
      "centre": "Silsden",
      "new_enquiries": 2,
      "new_test_drives": 1,
      "new_os": 1,
      "new_orders": 0,
      "used_enquiries": 14,
      "used_test_drives": 3,
      "used_os": 1,
      "used_orders": 1,
      "total_enquiries": 16,
      "total_test_drives": 4,
      "total_os": 2,
      "total_orders": 1,
      "lost_op_req": 0,
      "confirmed_orders": 0,
      "delivered": 8,
      "lost_opportunities": 6,
      "td_ratio": 0.25,
      "orders_ratio": 0.06,
      "os_ratio": 0.12
    }
  ]
};
